ignore: |
  /vendor

extends: default

yaml-files:
  - '*.yaml'
  - '*.yml'

rules:
  truthy: disable
  line-length: disable
  document-start: disable
  trailing-spaces: disable
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
