#!/usr/bin/env bash

. $(dirname $0)/util
set -eu

: ${PLATFORMS=}
: ${BUILDKIT_TARGET=}
: ${BUILDKITD_TAGS=}

buildArgs=""
if [ -n "$BUILDKIT_TARGET" ]; then
  buildArgs="--build-arg=BUILDKIT_TARGET=$BUILDKIT_TARGET "
fi
if [ -n "$BUILDKITD_TAGS" ]; then
  buildArgs="--build-arg=BUILDKITD_TAGS=\"$BUILDKITD_TAGS\" "
fi

platformFlag=""
if [ -n "$PLATFORMS" ]; then
  platformFlag="--platform=$PLATFORMS"
fi

buildxCmd build $platformFlag $buildArgs \
  --target "binaries" \
  --output "type=local,dest=./bin/" \
  .
