#!/usr/bin/env bash

. $(dirname $0)/util
set -e

if [ -z "$TRAVIS_COMMIT" ]; then
  echo "Travis commit required"
  exit 0
fi

exportCacheFlags=""
exportFlags=""
if [ -f /tmp/buildkit-ci-cache-repo ]; then
  exportCacheFlags="--cache-to=type=inline"
  exportFlags="--output=type=image,push=true,name=$(cat /tmp/buildkit-ci-cache-repo)"
fi

set -x

docker buildx build $progressFlag \
  --target "binaries" \
  --cache-from "type=registry,ref=cicache.buildk.it/moby/buildkit/master:binaries" \
  --cache-from "type=registry,ref=cicache.buildk.it/moby/buildkit/master:integration-tests" \
  $exportCacheFlags $exportFlags:binaries \
  $currentcontext

docker buildx build $progressFlag \
  --target "integration-tests-base" \
  --cache-from "type=registry,ref=cicache.buildk.it/moby/buildkit/master:integration-tests" \
  $exportCacheFlags $exportFlags:integration-tests \
  $currentcontext
