#!/usr/bin/env bash

. $(dirname $0)/util
set -e

: ${PLATFORMS=windows/amd64}

importCacheFlags=""
if [ -n "$cacheref" ]; then
  if [ "$cachetype" = "local" ]; then
    currentcontext="."
    importCacheFlags="--cache-from=type=local,src=$cacheref"
  else
    importCacheFlags="--cache-from=type=registry,ref=cicache.buildk.it/moby/buildkit/master:binaries"
  fi
fi

buildxCmd build $importCacheFlags \
  --target "buildkit-buildkitd" \
  --platform "$PLATFORMS" \
  $currentcontext
