#!/usr/bin/env bash

TYP=$1

. $(dirname $0)/util
set -e

usage() {
  echo "usage: ./hack/build_ci_first_pass <binaries|integration-tests>"
  exit 1
}

if [ -z "$TYP" ]; then
  usage
fi

importCacheFlags=""
exportCacheFlags=""
if [ "$GITHUB_ACTIONS" = "true" ]; then
  if [ -n "$cacheref" ]; then
    importCacheFlags="--cache-from=type=local,src=$cacheref"
    exportCacheFlags="--cache-to=type=local,dest=$cacheref"
  fi
fi

case $TYP in
  "binaries")
    buildxCmd build $importCacheFlags $exportCacheFlags \
      --target "binaries" \
      $currentcontext
    ;;
  "integration-tests")
    buildxCmd build $importCacheFlags $exportCacheFlags \
      --target "integration-tests-base" \
      $currentcontext
    ;;
  *)
    echo >&2 "Unknown type $TYP"
    exit 1
    ;;
esac
