#!/usr/bin/env bash

TAG=$1
REPO=$2
PUSH=$3

. $(dirname $0)/util
set -eu -o pipefail

: ${PLATFORMS=linux/amd64}
: ${TARGET=}

versionTag=$(git describe --always --tags --match "v[0-9]*")

if [[ ! "$versionTag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  versionTag=""
fi

usage() {
  echo "usage: $0 <tag> <repo> [push]"
  exit 1
}

if [ -z "$TAG" ] || [ -z "$REPO" ]; then
  usage
fi

pushFlag="push=false"
if [ "$PUSH" = "push" ]; then
  pushFlag="push=true"
fi

targetFlag=""
if [ -n "$TARGET" ]; then
  targetFlag="--target=$TARGET"
fi

tagLatest=""
if [[ "$versionTag" == "$TAG" ]]; then
  if [ -n "$TARGET" ]; then
    tagLatest=",$REPO:$TARGET"
  else
    tagLatest=",$REPO:latest"
  fi
fi

importCacheFlags=""
exportCacheFlags=""
if [ -n "$cacheref" ]; then
  if [ "$cachetype" = "local" ]; then
    importCacheFlags="--cache-from=type=local,src=$cacheref"
    exportCacheFlags="--cache-to=type=local,dest=$cacheref"
  else
    importCacheFlags="--cache-from=type=registry,ref=$REPO:$TAG$tagLatest"
    exportCacheFlags="--cache-to=type=inline"
  fi
fi

set -x

docker buildx build $progressFlag $targetFlag $importCacheFlags $exportCacheFlags \
  --platform "$PLATFORMS" \
  --tag "$REPO:$TAG$tagLatest" \
  --output "type=image,$pushFlag" \
  .
