#!/usr/bin/env bash

. $(dirname $0)/util
set -eu -o pipefail -x

lintLegacy() {
  docker build -f ./hack/dockerfiles/lint.Dockerfile --force-rm .
}

lintDocker() {
  export DOCKER_BUILDKIT=1
  iidfile=$(mktemp -t docker-iidfile.XXXXXXXXXX)
  docker build --iidfile $iidfile -f ./hack/dockerfiles/lint.buildkit.Dockerfile --force-rm .
  iid=$(cat $iidfile)
  docker rmi $iid
  rm -f $iidfile
}

lint() {
  buildctl build --frontend=dockerfile.v0 \
    --local context=. --local dockerfile=. \
    --frontend-opt filename=./hack/dockerfiles/lint.buildkit.Dockerfile
}

case $buildmode in
"buildkit")
  lint
  ;;
"docker-buildkit")
  lintDocker
  ;;
*)
  lintLegacy
  ;;
esac
