#!/usr/bin/env bash

TAG=$1
OUT=$2

. $(dirname $0)/util
set -eu -o pipefail

: ${PLATFORMS=linux/amd64}

usage() {
  echo "usage: ./hack/release-tar <tag> <out>"
  exit 1
}

if [ -z "$TAG" ] || [ -z "$OUT" ]; then
  usage
fi

buildxCmd build $cacheFromFlags \
  --target release \
  --platform "$PLATFORMS" \
  --output "type=local,dest=$OUT" \
  $currentcontext
