#!/usr/bin/env bash

set -e

function clean() {
  docker rmi $(cat $iidfile)
}

iidfile=$(mktemp -t docker-iidfile.XXXXXXXXXX)
DOCKER_BUILDKIT=1 docker build --iidfile $iidfile --build-arg BUILDKIT_DEBUG --target dev-env .

BUILDKIT_REGISTRY_MIRROR_DIR="/root/.cache/registry"

ENV="-e DELVE_PORT -e BUILDKIT_REGISTRY_MIRROR_DIR"

trap clean EXIT
SSH=
if [ -n "$MOUNT_SSH_AUTH_SOCK" ]; then
  SSH="-v $SSH_AUTH_SOCK:$SSH_AUTH_SOCK -e SSH_AUTH_SOCK"
fi

volumes="-v /tmp"
if [ -n "$MOUNT_BUILDKIT_SOURCE" ]; then
  volumes="$volumes -v $(pwd):/src"
fi

if [ -n "$DELVE_PORT" ]; then
  DELVE_PORT_FORWARD="-p $DELVE_PORT"
fi

DOCKER_FLAGS="-it --rm --privileged --name=buildkit-dev $SSH $volumes $ENV $DELVE_PORT_FORWARD"

set -x
docker run $DOCKER_FLAGS $(cat $iidfile) ash
