#!/usr/bin/env bash

set -eu -o pipefail -x

# update this to iidfile after 17.06
docker build -t buildkit:test --target unit-tests -f ./hack/dockerfiles/test.Dockerfile --force-rm .
docker run --rm buildkit:test go build ./...
docker run -e GOOS=darwin --rm buildkit:test go build ./cmd/buildctl