#!/usr/bin/env bash

set -eu -o pipefail -x

# update this to iidfile after 17.06
docker build -t buildkit_poc:vendor -f ./hack/dockerfiles/vendor.Dockerfile --force-rm .
cid=$(docker create buildkit_poc:vendor noop)
rm -rf ./vendor
docker cp $cid:/go/src/github.com/tonistiigi/buildkit_poc/vendor .
docker rm $cid