#!/usr/bin/env bash

. $(dirname $0)/util
set -eu

output=$(mktemp -d -t buildctl-output.XXXXXXXXXX)

buildxCmd build \
  --target "update" \
  --output "type=local,dest=$output" \
  --file "./hack/dockerfiles/generated-files.Dockerfile" \
  .

cp -R "$output/." .
rm -rf $output
