#!/usr/bin/env sh
export BUILDX_NO_DEFAULT_LOAD=true

: ${CONTINUOUS_INTEGRATION=}
: ${CI=}
: ${GITHUB_ACTIONS=}
: ${DOCKER_BUILDKIT=}
: ${TRAVIS_EVENT_TYPE=}
: ${TRAVIS_BRANCH=}
: ${CACHE_DIR=}

progressFlag=""
if [ "$CONTINUOUS_INTEGRATION" = "true" ] || [ "$CI" = "true" ]; then
  progressFlag="--progress=plain"
fi

buildmode="buildkit"
buildxCmd() {
  if docker buildx version >/dev/null 2>&1; then
    set -x
    docker buildx "$@" $progressFlag
  elif buildx version >/dev/null 2>&1; then
    set -x
    buildx "$@" $progressFlag
  elif docker version >/dev/null 2>&1; then
    set -x
    DOCKER_BUILDKIT=1 docker "$@" $progressFlag
  else
    echo >&2 "ERROR: Please enable DOCKER_BUILDKIT or install standalone buildx"
    exit 1
  fi
}

cachetype=""
cacheref=""
currentref=""
if [ "$GITHUB_ACTIONS" = "true" ]; then
  currentref="git://github.com/$GITHUB_REPOSITORY#$GITHUB_REF"
  cachetype="local"
  cacheref="$CACHE_DIR"
elif [ "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then
  currentref="git://github.com/moby/buildkit#refs/pull/$TRAVIS_PULL_REQUEST/merge"
  cachetype="registry"
  cacheref="cicache.buildk.it/moby/buildkit/pr$TRAVIS_BUILD_ID"
elif [ -n "$TRAVIS_BRANCH" ]; then
  currentref="git://github.com/$TRAVIS_REPO_SLUG#$TRAVIS_BRANCH"
fi

currentcontext="."
currentcontextBuildctl="--local context=. --local dockerfile=."
if [ -n "$currentref" ]; then
  currentcontext="--build-arg BUILDKIT_CONTEXT_KEEP_GIT_DIR=1 $currentref"
  currentcontextBuildctl="--opt context=$currentref --opt build-arg:BUILDKIT_CONTEXT_KEEP_GIT_DIR=1"
fi
