#!/usr/bin/env bash

set -eu -o pipefail -x

iidfile=$(mktemp -t docker-iidfile.XXXXXXXXXX)
docker build --build-arg VNDR_VERSION=15dc0965b7ba6dd78ae741e6fda33f23207033c4 --iidfile $iidfile -f ./hack/dockerfiles/vendor.Dockerfile --force-rm .
iid=$(cat $iidfile)
diffs="$(docker run --rm $iid git status --porcelain -- vendor 2>/dev/null)"
if [ "$diffs" ]; then
    {
        set +x
        echo 'The result of vndr differs'
        echo
        echo "$diffs"
        echo
        echo 'Please vendor your package with github.com/LK4D4/vndr.'
        echo
    } >&2
    false
fi
echo 'Congratulations! All vendoring changes are done the right way.'
rm -f $iidfile
