#!/usr/bin/env bash

. $(dirname $0)/util
set -eu

buildxCmd build \
  --target "validate" \
  --output "type=cacheonly" \
  --file "./hack/dockerfiles/generated-files.Dockerfile" \
  .

buildxCmd build \
  --target "validate-toc" \
  --output "type=cacheonly" \
  --file "./hack/dockerfiles/generated-files.Dockerfile" \
  .
