name: buildkit
services:
  buildkit:
    container_name: buildkit-dev
    build:
      context: ../..
    image: moby/buildkit:local
    ports:
      - 127.0.0.1:5000:5000
      - 127.0.0.1:6060:6060
    restart: always
    privileged: true
    configs:
      - source: buildkit_config
        target: /etc/buildkit
    volumes:
      - buildkit:/var/lib/buildkit

volumes:
  buildkit:

configs:
  buildkit_config:
    file: ./buildkit
