name: dockerfile-release-test

on:
  workflow_dispatch:
  push:
    branches:
      - testing/dockerfile-test-versioning

env:
  TESTFLAGS: "-v --parallel=6 --timeout=30m"

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        ref:
          - dockerfile/1.12.1
          - dockerfile/1.12.0
          - dockerfile/1.11.0
          - dockerfile/1.10.0
          - dockerfile/1.9.0
          - dockerfile/1.8.1
          - dockerfile/1.7.1
          - dockerfile/1.6.0
          - dockerfile/1.5.2
        channel:
          - mainline
          - labs

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - name: Test
        run: |
          DOCKERFILE_RELEASES=${{ matrix.channel }} TEST_SUITE_CONTEXT=https://github.com/${GITHUB_REPOSITORY}.git#${{ matrix.ref }} TESTPKGS=./frontend/dockerfile ./hack/test dockerfile