name: pr-assign-author

permissions:
  contents: read

on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  run:
    uses: crazy-max/.github/.github/workflows/pr-assign-author.yml@20ef82212dc54bab5749f5e05576ca6d3c8a5773
    permissions:
      contents: read
      pull-requests: write
