name: pr-assign-author

permissions:
  contents: read

on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  run:
    uses: crazy-max/.github/.github/workflows/pr-assign-author.yml@71eec88cb5c2185e8209fab03eeb1f4c76129642
    permissions:
      contents: read
      pull-requests: write
