name: pr-assign-author

permissions:
  contents: read

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers] does not checkout, safe to use pull_request_target
    types:
      - opened
      - reopened

jobs:
  run:
    uses: crazy-max/.github/.github/workflows/pr-assign-author.yml@46267a6e61cd56aac2fc79943df180152f4c89d6 # v1.10.1
    permissions:
      contents: read
      pull-requests: write
